name: Py

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./python
    steps:
      - name: Hello world
        run: |
          echo "Hello World"
          ls /home/runner/work/hoardbase/hoardbase/python
          ls /home/runner/work/hoardbase/hoardbase
          ls /home/runner/work/hoardbase
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release -m /home/runner/work/hoardbase/hoardbase/python/Cargo.toml
